<?php
/**
 * Created by PhpStorm.
 * User: lixingbo
 * Date: 2019/1/16
 * Time: 下午4:46
 */

namespace Ddup\Logger\Test;


use Ddup\Logger\Aliyun\AliyunLogger;
use Ddup\Logger\Aliyun\Config\AliyunLogStruct;
use Psr\Log\LoggerInterface;

class AliLoggerTest extends TestCase
{

    /**
     * @var LoggerInterface
     */
    private $client;

    protected function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->client = new AliyunLogger(new AliyunLogStruct([
            'access_key_id'     => '',
            'access_key_secret' => '',
            'endpoint'          => '',
            'project'           => '',
            'store'             => '',
            'topic'             => ''
        ]));

        $this->client->setTopic('logger-topic');
    }

    public function test_write()
    {
        $this->client->info('别紧张，只是测试', [
            'con' => '登高一呼时才懂，始终在为你心痛'
        ]);

        $this->assertTrue(true);
    }

    public function test_level()
    {
        $this->client->error('等级error', [
            'con' => '登高一呼时才懂，始终在为你心痛'
        ]);

        $this->client->debug('等级debug', [
            'con' => '登高一呼时才懂，始终在为你心痛'
        ]);

        $this->assertTrue(true);
    }
}