<?php
/**
 * Created by PhpStorm.
 * User: lixingbo
 * Date: 2019/1/16
 * Time: 下午4:20
 */

namespace Ddup\Logger\Test;


use Ddup\Logger\Cli\CliLogger;
use Psr\Log\LoggerInterface;

class CliLoggerTest extends TestCase
{
    /**
     * @var LoggerInterface
     */
    private $logger;

    protected function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->logger = new CliLogger();
    }

    function test_write()
    {
        $this->logger->warning('黄颜色');
        $this->logger->error('红颜色');
        $this->logger->notice('蓝颜色');
        $this->logger->debug('紫颜色');
        $this->logger->info('绿颜色');

        $this->assertTrue(true);
    }
}